import React from 'react';
import { CZON_VERSION } from '../../version';

export const CZONFooter: React.FC = () => {
  return (
    <p className="text-center text-sm text-gray-500 my-8">
      Generated by{' '}
      <strong>
        <a href="https://czon.zccz14.com">CZON@{CZON_VERSION}</a>
      </strong>{' '}
      •{' '}
      <a href="https://github.com/zccz14/CZON" target="_blank">
        GitHub
      </a>
    </p>
  );
};
