#!/usr/bin/env node

import { Command } from 'commander';
import { ZenBuilder } from './builder';
import { ZenConfig } from './types';
import * as path from 'path';
import * as fs from 'fs/promises';

const program = new Command();

program
  .name('zengen')
  .description('ZEN - A minimalist Markdown documentation site builder')
  .version('0.1.0');

// 构建命令
program
  .command('build')
  .description('Build documentation site from Markdown files')
  .argument('<src-dir>', 'Source directory containing Markdown files')
  .option('-o, --out <dir>', 'Output directory for generated HTML', 'dist')
  .option('-t, --template <file>', 'Custom template file')
  .option('-w, --watch', 'Watch for changes and rebuild automatically')
  .option('-v, --verbose', 'Show detailed output')
  .option('-c, --config <file>', 'Configuration file')
  .option('--clean', 'Clean output directory before building')
  .action(async (srcDir, options) => {
    try {
      // 加载配置文件
      let config: ZenConfig = {};
      if (options.config) {
        try {
          const configPath = path.resolve(options.config);
          const configContent = await fs.readFile(configPath, 'utf-8');
          config = JSON.parse(configContent);
        } catch (error) {
          console.error(`❌ Failed to load config file:`, error);
          process.exit(1);
        }
      }

      // 合并命令行参数和配置
      const buildOptions = {
        srcDir: path.resolve(srcDir),
        outDir: path.resolve(options.out),
        template: options.template ? path.resolve(options.template) : undefined,
        watch: options.watch,
        verbose: options.verbose
      };

      const builder = new ZenBuilder(config);

      // 验证配置
      const errors = builder.validateConfig(config);
      if (errors.length > 0) {
        console.error('❌ Configuration errors:');
        errors.forEach(error => console.error(`  - ${error}`));
        process.exit(1);
      }

      // 清理输出目录
      if (options.clean) {
        await builder.clean(buildOptions.outDir);
      }

      // 构建或监听
      if (options.watch) {
        await builder.watch(buildOptions);
      } else {
        await builder.build(buildOptions);
      }
    } catch (error) {
      console.error('❌ Build failed:', error);
      process.exit(1);
    }
  });

// 清理命令
program
  .command('clean')
  .description('Clean output directory')
  .argument('<dir>', 'Directory to clean')
  .action(async (dir) => {
    try {
      const builder = new ZenBuilder();
      await builder.clean(path.resolve(dir));
    } catch (error) {
      console.error('❌ Clean failed:', error);
      process.exit(1);
    }
  });

// 初始化命令
program
  .command('init')
  .description('Initialize a new ZEN project')
  .option('-d, --dir <directory>', 'Target directory', '.')
  .action(async (options) => {
    try {
      const targetDir = path.resolve(options.dir);

      // 创建目录结构
      await fs.mkdir(path.join(targetDir, 'docs'), { recursive: true });
      await fs.mkdir(path.join(targetDir, 'static'), { recursive: true });

      // 创建示例文档
      const exampleDoc = `# Welcome to ZEN

This is an example documentation page generated by ZEN.

## Getting Started

1. Write your documentation in Markdown format
2. Run \`zengen build docs --out dist\`
3. Open the generated HTML files in your browser

## Features

- **Minimal configuration**: Focus on writing, not configuration
- **Smart navigation**: Automatic navigation generation
- **Beautiful templates**: Clean, responsive design
- **Code highlighting**: Syntax highlighting for code blocks

## Example Code

\`\`\`javascript
// This is a JavaScript example
console.log('Hello ZEN!');
\`\`\`

---

*Happy documenting!*`;

      await fs.writeFile(
        path.join(targetDir, 'docs', 'index.md'),
        exampleDoc,
        'utf-8'
      );

      // 创建配置文件
      const config = {
        srcDir: './docs',
        outDir: './dist',
        template: undefined,
        i18n: {
          sourceLang: 'en-US',
          targetLangs: ['zh-CN', 'ja-JP']
        }
      };

      await fs.writeFile(
        path.join(targetDir, 'zen.config.json'),
        JSON.stringify(config, null, 2),
        'utf-8'
      );

      // 创建 package.json 脚本（如果不存在）
      const packageJsonPath = path.join(targetDir, 'package.json');
      try {
        const packageJson = JSON.parse(await fs.readFile(packageJsonPath, 'utf-8'));

        if (!packageJson.scripts) {
          packageJson.scripts = {};
        }

        packageJson.scripts.build = 'zengen build docs --out dist';
        packageJson.scripts['build:watch'] = 'zengen build docs --out dist --watch';
        packageJson.scripts.clean = 'zengen clean dist';

        await fs.writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2), 'utf-8');
      } catch (error) {
        // package.json 不存在，创建简单的版本
        const simplePackageJson = {
          name: 'zen-docs',
          version: '1.0.0',
          scripts: {
            build: 'zengen build docs --out dist',
            'build:watch': 'zengen build docs --out dist --watch',
            clean: 'zengen clean dist'
          }
        };

        await fs.writeFile(
          packageJsonPath,
          JSON.stringify(simplePackageJson, null, 2),
          'utf-8'
        );
      }

      console.log(`
🎉 ZEN project initialized successfully!

Next steps:
1. Add your Markdown files to the 'docs' directory
2. Run 'npm run build' to generate the site
3. Run 'npm run build:watch' for development with auto-reload

Project structure:
${targetDir}/
├── docs/           # Your documentation files
│   └── index.md    # Example document
├── static/         # Static assets (images, CSS, JS)
├── zen.config.json # Configuration file
└── package.json    # npm scripts

For more information, visit: https://github.com/yourusername/zen
      `);
    } catch (error) {
      console.error('❌ Initialization failed:', error);
      process.exit(1);
    }
  });

// 信息命令
program
  .command('info')
  .description('Show information about ZEN')
  .action(() => {
    console.log(`
🤖 ZEN - A minimalist Markdown documentation site builder

Version: 0.1.0
Description: Build beautiful documentation sites from Markdown files

Features:
  • Minimal configuration required
  • Smart navigation generation
  • Beautiful, responsive templates
  • Code syntax highlighting
  • Watch mode for development
  • Sitemap generation
  • Static asset support

Commands:
  build     Build documentation site
  clean     Clean output directory
  init      Initialize new project
  info      Show this information

Examples:
  $ zengen build ./docs --out ./dist
  $ zengen build ./docs --out ./dist --watch
  $ zengen init --dir ./my-docs
  $ zengen clean ./dist

For more help, run: zengen --help
    `);
  });

// 默认命令（兼容旧格式）
program
  .argument('[src-dir]', 'Source directory')
  .option('-o, --out <dir>', 'Output directory')
  .option('-t, --template <file>', 'Custom template file')
  .option('-w, --watch', 'Watch for changes')
  .option('-v, --verbose', 'Show detailed output')
  .action(async (srcDir, options) => {
    if (!srcDir) {
      program.help();
      return;
    }

    try {
      const builder = new ZenBuilder();

      const buildOptions = {
        srcDir: path.resolve(srcDir),
        outDir: path.resolve(options.out || 'dist'),
        template: options.template ? path.resolve(options.template) : undefined,
        watch: options.watch,
        verbose: options.verbose
      };

      if (options.watch) {
        await builder.watch(buildOptions);
      } else {
        await builder.build(buildOptions);
      }
    } catch (error) {
      console.error('❌ Build failed:', error);
      process.exit(1);
    }
  });

// 错误处理
program.showHelpAfterError();
program.showSuggestionAfterError();

// 解析命令行参数
program.parse(process.argv);

// 如果没有参数，显示帮助
if (process.argv.length <= 2) {
  program.help();
}