#!/usr/bin/env node

import { Command } from 'commander';
import { ZenBuilder } from './builder';
import { ZenConfig } from './types';
import * as path from 'path';
import * as fs from 'fs/promises';
import * as fsSync from 'fs';
import * as url from 'url';

// 获取版本号 - 从 package.json 读取
// 注意：在构建时，版本号会被替换为当前 package.json 中的版本
function getVersion(): string {
  return '0.1.2'; // 这个值会在构建时被替换
}

const program = new Command();

program
  .name('zengen')
  .description('ZEN - A minimalist Markdown documentation site builder')
  .version(getVersion());

// 构建命令
program
  .command('build')
  .description('Build documentation site from Markdown files in current directory')
  .option('-t, --template <file>', 'Custom template file')
  .option('-w, --watch', 'Watch for changes and rebuild automatically')
  .option('-s, --serve', 'Start HTTP server for preview (requires --watch)')
  .option('-p, --port <number>', 'HTTP server port', '3000')
  .option('--host <host>', 'HTTP server host', 'localhost')
  .option('-v, --verbose', 'Show detailed output')
  .option('-c, --config <file>', 'Configuration file')
  .option('--base-url <url>', 'Base URL for generated links (e.g., https://example.com/docs)')
  .option('--clean', 'Clean output directory before building')
  .action(async (options) => {
    try {
      // 加载配置文件
      let config: ZenConfig = {};
      if (options.config) {
        try {
          const configPath = path.resolve(options.config);
          const configContent = await fs.readFile(configPath, 'utf-8');
          config = JSON.parse(configContent);
        } catch (error) {
          console.error(`❌ Failed to load config file:`, error);
          process.exit(1);
        }
      }

      // 强制使用当前目录作为 src 目录，输出到 .zen/dist 目录
      const currentDir = process.cwd();
      const outDir = path.join(currentDir, '.zen', 'dist');

      // 合并命令行参数和配置
      const buildOptions = {
        srcDir: currentDir,
        outDir: outDir,
        template: options.template ? path.resolve(options.template) : undefined,
        watch: options.watch,
        serve: options.serve,
        port: parseInt(options.port, 10),
        host: options.host,
        verbose: options.verbose,
        baseUrl: options.baseUrl || config.baseUrl
      };


      const builder = new ZenBuilder(config);

      // 验证配置
      const errors = builder.validateConfig(config);
      if (errors.length > 0) {
        console.error('❌ Configuration errors:');
        errors.forEach(error => console.error(`  - ${error}`));
        process.exit(1);
      }

      // 警告 --serve 选项需要 --watch 选项
      if (options.serve && !options.watch) {
        console.warn('⚠️ Warning: --serve option requires --watch option, ignoring --serve');
        buildOptions.serve = false;
      }

      // 清理输出目录
      if (options.clean) {
        await builder.clean(buildOptions.outDir);
      }

      // 构建或监听
      if (options.watch) {
        await builder.watch(buildOptions);
      } else {
        await builder.build(buildOptions);
      }
    } catch (error) {
      console.error('❌ Build failed:', error);
      process.exit(1);
    }
  });

// 清理命令
program
  .command('clean')
  .description('Clean .zen/dist output directory')
  .action(async () => {
    try {
      const builder = new ZenBuilder();
      const currentDir = process.cwd();
      const outDir = path.join(currentDir, '.zen', 'dist');
      await builder.clean(outDir);
    } catch (error) {
      console.error('❌ Clean failed:', error);
      process.exit(1);
    }
  });

// 初始化命令
program
  .command('init')
  .description('Initialize a new ZEN project')
  .option('-d, --dir <directory>', 'Target directory', '.')
  .action(async (options) => {
    try {
      const targetDir = path.resolve(options.dir);

      // 创建目录结构
      await fs.mkdir(path.join(targetDir, 'static'), { recursive: true });

      // 创建示例文档
      const exampleDoc = `# Welcome to ZEN

This is an example documentation page generated by ZEN.

## Getting Started

1. Write your documentation in Markdown format in current directory
2. Run \`zengen build\`
3. Open the generated HTML files in your browser at .zen/dist

## Features

- **Minimal configuration**: Focus on writing, not configuration
- **Smart navigation**: Automatic navigation generation
- **Beautiful templates**: Clean, responsive design
- **Code highlighting**: Syntax highlighting for code blocks

## Example Code

\`\`\`javascript
// This is a JavaScript example
console.log('Hello ZEN!');
\`\`\`

---

*Happy documenting!*`;

      await fs.writeFile(
        path.join(targetDir, 'index.md'),
        exampleDoc,
        'utf-8'
      );

      // 创建配置文件
      const config = {
        template: undefined,
        i18n: {
          sourceLang: 'en-US',
          targetLangs: ['zh-CN', 'ja-JP']
        }
      };

      await fs.writeFile(
        path.join(targetDir, 'zen.config.json'),
        JSON.stringify(config, null, 2),
        'utf-8'
      );

      // 创建 package.json 脚本（如果不存在）
      const packageJsonPath = path.join(targetDir, 'package.json');
      try {
        const packageJson = JSON.parse(await fs.readFile(packageJsonPath, 'utf-8'));

        if (!packageJson.scripts) {
          packageJson.scripts = {};
        }

        packageJson.scripts.build = 'zengen build';
        packageJson.scripts['build:watch'] = 'zengen build --watch';
        packageJson.scripts['build:serve'] = 'zengen build --watch --serve';
        packageJson.scripts.clean = 'zengen clean';

        await fs.writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2), 'utf-8');
      } catch (error) {
        // package.json 不存在，创建简单的版本
        const simplePackageJson = {
          name: 'zen-docs',
          version: '1.0.0',
          scripts: {
            build: 'zengen build',
            'build:watch': 'zengen build --watch',
            'build:serve': 'zengen build --watch --serve',
            clean: 'zengen clean'
          }
        };

        await fs.writeFile(
          packageJsonPath,
          JSON.stringify(simplePackageJson, null, 2),
          'utf-8'
        );
      }

      console.log(`
🎉 ZEN project initialized successfully!

Next steps:
1. Add your Markdown files to the current directory
2. Run 'npm run build' to generate the site (output will be in .zen/dist)
3. Run 'npm run build:watch' for development with auto-reload
4. Run 'npm run build:serve' for development with auto-reload and HTTP server

Project structure:
${targetDir}/
├── index.md        # Example document (in current directory)
├── static/         # Static assets (images, CSS, JS)
├── zen.config.json # Configuration file
└── package.json    # npm scripts

For more information, visit: https://github.com/yourusername/zen
      `);
    } catch (error) {
      console.error('❌ Initialization failed:', error);
      process.exit(1);
    }
  });

// 信息命令
program
  .command('info')
  .description('Show information about ZEN')
  .action(() => {
    console.log(`
🤖 ZEN - A minimalist Markdown documentation site builder

Version: 0.1.0
Description: Build beautiful documentation sites from Markdown files

Features:
  • Minimal configuration required
  • Smart navigation generation
  • Beautiful, responsive templates
  • Code syntax highlighting
  • Watch mode for development
  • Sitemap generation
  • Static asset support

Commands:
  build     Build documentation site
  clean     Clean output directory
  init      Initialize new project
  info      Show this information

Examples:
  $ zengen build
  $ zengen build --watch
  $ zengen build --watch --serve
  $ zengen build --watch --serve --port 8080
  $ zengen init --dir ./my-docs
  $ zengen clean

For more help, run: zengen --help
    `);
  });


// 错误处理
program.showHelpAfterError();
program.showSuggestionAfterError();

// 解析命令行参数
program.parse(process.argv);

// 如果没有参数，显示帮助
if (process.argv.length <= 2) {
  program.help();
}